### ISSUE TITLE
grpc を version 1.1にする

### ISSUE THREAD

**Issue by kyohei-shimada** [bm-sms/kaigojob-legacy-facade-grpc#2]

**Comment by kyohei-shimada** [comment]
https://github.com/bm-sms/kaigojob-legacy-facade-grpc/blob/31a80e0a7c698019ae9af8f2f2df35e19cf24c6e/docker-compose.yml#L5

のイメージが1.0に依存している 😱 ので対応され次第．
gemspecのgrpcとともにバージョンアップする．

see also: https://github.com/bm-sms/kaigojob-rails/issues/46

**Comment by tkywtnb** [comment]
1.12 に上げたので close
